# Generated by Django 5.0 on 2023-12-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finchild', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobChallanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('hardness', models.IntegerField()),
                ('image', models.ImageField(upload_to='JobImage/')),
                ('income', models.IntegerField()),
                ('estimated_time', models.IntegerField()),
                ('challange', models.TextField()),
                ('answers', models.TextField()),
            ],
        ),
    ]
