# Generated by Django 5.0 on 2023-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finchild', '0002_jobchallanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='happines',
            field=models.FloatField(default=0.0),
        ),
    ]
