# Generated by Django 5.0 on 2023-12-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finchild', '0003_user_happines'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopentity',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='happines',
            field=models.IntegerField(default=0),
        ),
    ]
