# Generated by Django 5.0 on 2023-12-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finchild', '0004_shopentity_quantity_alter_user_happines'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopentity',
            name='happines',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
